import test, {beforeEach, afterEach} from 'node:test';
const realNow=Date.now;
beforeEach(()=>{Date.now=()=>Date.parse('2026-09-25T00:00:00Z');});
afterEach(()=>{Date.now=realNow;});
import assert from 'node:assert/strict';
import worker, {boundedJSON,validInput} from '../worker.mjs';
const origin='https://hitokoto.example';
const day=new Date().toISOString().slice(0,10);
class Quota {
  constructor(initial={}) {this.rows=new Map(Object.entries(initial));this.bindings=[];}
  prepare(sql) {const self=this;return {bind(...values){self.bindings.push(values);return {
    async all(){return {results:values.filter(k=>self.rows.has(k)).map(key=>({key,count:self.rows.get(key)}))};},
    async first(){assert.match(sql,/ON CONFLICT\(key\) DO UPDATE SET count=count\+1 WHERE count < \?/);const [key,limit]=values;const n=self.rows.get(key)||0;if(n>=limit)return null;self.rows.set(key,n+1);return {count:n+1};},
    async run(){assert.match(sql,/DELETE FROM quota/);return {success:true};}
  };}};}
}
function setup(initial={}) {const db=new Quota(initial),calls=[];return {db,calls,env:{QUOTA:db,QUOTA_SALT:'test-only-salt',AI:{async run(model,input){calls.push({model,input});return {response:JSON.parse(input.messages[1].content).text+'。'};}}}};}
function request(data={text:'接客がよかった',storeName:'架空デモ'},extra={}) {return new Request(origin+'/api/draft',{method:'POST',headers:{origin,'content-type':'application/json','cf-connecting-ip':'192.0.2.4',...extra},body:JSON.stringify(data)});}
async function invoke(req,env) {const pending=[];const r=await worker.fetch(req,env,{waitUntil(p){pending.push(p);}});await Promise.allSettled(pending);return {status:r.status,body:await r.json()};}
test('valid input limits and control characters',()=>{for(const v of [null,{}, {text:' ',storeName:'s'},{text:'a'.repeat(601),storeName:'s'},{text:'x',storeName:'a'.repeat(81)},{text:'bad\u0000',storeName:'s'}])assert.ok(!validInput(v));assert.ok(validInput({text:'不満\nもある',storeName:'s'}));});
test('bounded body rejects invalid UTF8 and oversize streamed bytes',async()=>{await assert.rejects(boundedJSON(new Request(origin,{method:'POST',body:new Uint8Array([255])})));await assert.rejects(boundedJSON(new Request(origin,{method:'POST',body:' '.repeat(4097)})),/large/);});
test('origin, method, MIME, JSON rejected before AI',async()=>{const s=setup();assert.equal((await invoke(request(undefined,{origin:'https://evil.example'}),s.env)).status,403);assert.equal((await invoke(request(undefined,{'content-type':'text/plain'}),s.env)).status,415);assert.equal((await invoke(new Request(origin+'/api/draft'),s.env)).status,405);assert.equal((await invoke(new Request(origin+'/api/draft',{method:'POST',headers:{origin,'content-type':'application/json'},body:'{'}),s.env)).status,400);assert.equal(s.calls.length,0);});
test('missing bindings and IP preserve original trimmed feedback',async()=>{for(const key of ['AI','QUOTA','QUOTA_SALT']){const s=setup();delete s.env[key];assert.deepEqual((await invoke(request({text:'  不満があります  ',storeName:'s'}),s.env)).body,{draft:'不満があります',mode:'fallback'});assert.equal(s.calls.length,0);}const s=setup();const req=request();req.headers.delete('cf-connecting-ip');assert.equal((await invoke(req,s.env)).body.mode,'fallback');assert.equal(s.calls.length,0);});
test('same IP has max 10 AI attempts under concurrency',async()=>{const s=setup();const responses=await Promise.all(Array.from({length:25},()=>invoke(request(),s.env)));assert.equal(s.calls.length,10);assert.equal(responses.filter(r=>r.body.mode==='ai').length,10);assert.equal(s.db.rows.get('total'),10);});
test('global daily and lifetime ceilings hold with distinct IPs',async()=>{for(const [key,ceiling] of [['day:'+day,100],['total',1000]]){const s=setup({[key]:ceiling-2});await Promise.all(Array.from({length:15},(_,i)=>invoke(request(undefined,{'cf-connecting-ip':'192.0.2.'+(i+10)}),s.env)));assert.equal(s.calls.length,2);assert.equal(s.db.rows.get(key),ceiling);}});
test('D1 outage prevents AI and stores no raw personal input',async()=>{const s=setup();await invoke(request(),s.env);assert.ok(!JSON.stringify(s.db.bindings).includes('192.0.2.4'));assert.ok(!JSON.stringify(s.db.bindings).includes('架空デモ'));assert.ok(!JSON.stringify(s.db.bindings).includes('接客'));s.env.QUOTA={prepare(){throw Error('offline');}};assert.equal((await invoke(request(),s.env)).body.mode,'fallback');assert.equal(s.calls.length,1);});
test('AI failures and unsafe output preserve feedback',async()=>{for(const output of ['', 'https://bad.example', '5つ星です','a'.repeat(801),null]){const s=setup();s.env.AI.run=async()=>({response:output});assert.deepEqual((await invoke(request({text:'不満です',storeName:'s'}),s.env)).body,{draft:'不満です',mode:'fallback'});}const s=setup();s.env.AI.run=async()=>{throw Error('model offline');};assert.equal((await invoke(request(),s.env)).body.mode,'fallback');});
test('AI timeout returns original at 10 seconds (mock clock)',async()=>{const s=setup();s.env.AI.run=()=>new Promise(()=>{});const old=globalThis.setTimeout;let timeout;globalThis.setTimeout=(fn,ms)=>{if(ms!==10000)return old(fn,ms);timeout=ms;queueMicrotask(fn);return 0;};try{assert.equal((await invoke(request(),s.env)).body.mode,'fallback');assert.equal(timeout,10000);}finally{globalThis.setTimeout=old;}});
test('API never sends a browser fetch or Google POST',async()=>{const old=globalThis.fetch;globalThis.fetch=()=>{throw Error('Unexpected network');};try{const s=setup();assert.equal((await invoke(request(),s.env)).body.mode,'ai');assert.equal(s.calls.length,1);}finally{globalThis.fetch=old;}});
test('static response has restrictive security policy',async()=>{const r=await worker.fetch(new Request(origin),{ASSETS:{fetch:async()=>new Response('<h1>demo</h1>')}},{});assert.match(r.headers.get('content-security-policy'),/connect-src 'self'/);assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.equal(r.headers.get('referrer-policy'),'no-referrer');});
test('meaning reversal and invented recommendation must fall back',async()=>{for(const output of ['最高でした。また来たい','不満です。また来ます','満足です']){const s=setup();s.env.AI.run=async()=>({response:output});assert.deepEqual((await invoke(request({text:'不満です',storeName:'s'}),s.env)).body,{draft:'不満です',mode:'fallback'});}});
test('punctuation and whitespace only remain eligible',async()=>{const s=setup();s.env.AI.run=async()=>({response:'「不満です。改善してほしい。」'});assert.deepEqual((await invoke(request({text:'不満です 改善してほしい',storeName:'s'}),s.env)).body,{draft:'「不満です。改善してほしい。」',mode:'ai'});});
test('unterminated body is bounded by a read deadline',async()=>{const old=globalThis.setTimeout;let timeout,cancelled=false;globalThis.setTimeout=(fn,ms)=>{timeout=ms;queueMicrotask(fn);return 0;};try{const body=new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('{'));},cancel(){cancelled=true;}});await assert.rejects(boundedJSON(new Request(origin,{method:'POST',body,duplex:'half'})));assert.equal(timeout,3000);assert.equal(cancelled,true);}finally{globalThis.setTimeout=old;}});

test("expiry stops AI even with all bindings available",async()=>{Date.now=()=>Date.parse("2026-10-09T00:00:00Z");const s=setup();assert.equal((await invoke(request(),s.env)).body.mode,"fallback");assert.equal(s.calls.length,0);});
