import test, {beforeEach, afterEach} from 'node:test';
const realNow=Date.now;
beforeEach(()=>{Date.now=()=>Date.parse('2026-09-25T00:00:00Z');});
afterEach(()=>{Date.now=realNow;});
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import worker, {boundedJSON,validInput} from '../worker.mjs';
const logs=[];const realWarn=console.warn,realError=console.error;
beforeEach(()=>{logs.length=0;console.warn=(...a)=>logs.push(['warn',...a]);console.error=(...a)=>logs.push(['error',...a]);});
afterEach(()=>{console.warn=realWarn;console.error=realError;});
const origin='https://hitokoto.example';
const day=new Date().toISOString().slice(0,10);
class Quota {
  constructor(initial={}) {this.rows=new Map(Object.entries(initial));this.bindings=[];}
  prepare(sql) {const self=this;return {bind(...values){self.bindings.push(values);return {
    async all(){return {results:values.filter(k=>self.rows.has(k)).map(key=>({key,count:self.rows.get(key)}))};},
    async first(){assert.match(sql,/ON CONFLICT\(key\) DO UPDATE SET count=count\+1 WHERE count < \?/);const [key,limit]=values;const n=self.rows.get(key)||0;if(n>=limit)return null;self.rows.set(key,n+1);return {count:n+1};},
    async run(){if(/^UPDATE quota SET count=MAX\(count-1,0\) WHERE key=\?$/.test(sql)){const [key]=values;self.rows.set(key,Math.max((self.rows.get(key)||0)-1,0));return {success:true};}assert.match(sql,/DELETE FROM quota/);return {success:true};}
  };}};}
}
// Real SQLite (D1 is SQLite) so the reserve/release/cleanup SQL is executed, not re-implemented by the mock.
async function sqliteQuota() {
  const emit=process.emitWarning;process.emitWarning=(w,...rest)=>String(w).includes('SQLite')?undefined:emit.call(process,w,...rest);
  let mod;try{mod=await import('node:sqlite');}catch{return null;}finally{process.emitWarning=emit;}
  const db=new mod.DatabaseSync(':memory:');db.exec(readFileSync(new URL('../schema.sql',import.meta.url),'utf8'));
  return {db,rows(){return Object.fromEntries(db.prepare('SELECT key,count FROM quota ORDER BY key').all().map(r=>[r.key,r.count]));},
    prepare(sql){const st=db.prepare(sql);return {bind(...v){return {async first(){return st.get(...v)??null;},async all(){return {results:st.all(...v)};},async run(){st.run(...v);return {success:true};}};}};}};
}
function setup(initial={}) {const db=new Quota(initial),calls=[];return {db,calls,env:{QUOTA:db,QUOTA_SALT:'test-only-salt',AI:{async run(model,input){calls.push({model,input});return {response:JSON.parse(input.messages[1].content).text+'。'};}}}};}
// Simulates the read-then-write window: the SELECT pre-check reports no ceiling while reserve() sees the real rows.
function staleRead(s) {const prep=s.db.prepare.bind(s.db);s.db.prepare=sql=>sql.startsWith('SELECT')?{bind(){return {async all(){return {results:[]};}};}}:prep(sql);return s;}
function request(data={text:'接客がよかった',storeName:'架空デモ'},extra={}) {return new Request(origin+'/api/draft',{method:'POST',headers:{origin,'content-type':'application/json','cf-connecting-ip':'192.0.2.4',...extra},body:JSON.stringify(data)});}
async function invoke(req,env) {const pending=[];const r=await worker.fetch(req,env,{waitUntil(p){pending.push(p);}});await Promise.allSettled(pending);return {status:r.status,body:await r.json()};}
test('valid input limits and control characters',()=>{for(const v of [null,{}, {text:' ',storeName:'s'},{text:'a'.repeat(601),storeName:'s'},{text:'x',storeName:'a'.repeat(81)},{text:'bad\u0000',storeName:'s'}])assert.ok(!validInput(v));assert.ok(validInput({text:'不満\nもある',storeName:'s'}));});
test('bounded body rejects invalid UTF8 and oversize streamed bytes',async()=>{await assert.rejects(boundedJSON(new Request(origin,{method:'POST',body:new Uint8Array([255])})));await assert.rejects(boundedJSON(new Request(origin,{method:'POST',body:' '.repeat(4097)})),/large/);});
test('origin, method, MIME, JSON rejected before AI',async()=>{const s=setup();assert.equal((await invoke(request(undefined,{origin:'https://evil.example'}),s.env)).status,403);assert.equal((await invoke(request(undefined,{'content-type':'text/plain'}),s.env)).status,415);assert.equal((await invoke(new Request(origin+'/api/draft'),s.env)).status,405);assert.equal((await invoke(new Request(origin+'/api/draft',{method:'POST',headers:{origin,'content-type':'application/json'},body:'{'}),s.env)).status,400);assert.equal(s.calls.length,0);});
test('missing bindings and IP preserve original trimmed feedback',async()=>{for(const key of ['AI','QUOTA','QUOTA_SALT']){const s=setup();delete s.env[key];assert.deepEqual((await invoke(request({text:'  不満があります  ',storeName:'s'}),s.env)).body,{draft:'不満があります',mode:'fallback'});assert.equal(s.calls.length,0);}const s=setup();const req=request();req.headers.delete('cf-connecting-ip');assert.equal((await invoke(req,s.env)).body.mode,'fallback');assert.equal(s.calls.length,0);});
test('same IP has max 10 AI attempts under concurrency',async()=>{const s=setup();const responses=await Promise.all(Array.from({length:25},()=>invoke(request(),s.env)));assert.equal(s.calls.length,10);assert.equal(responses.filter(r=>r.body.mode==='ai').length,10);assert.equal(s.db.rows.get('total'),10);});
test('global daily and lifetime ceilings hold with distinct IPs',async()=>{for(const [key,ceiling] of [['day:'+day,100],['total',1000]]){const s=setup({[key]:ceiling-2});await Promise.all(Array.from({length:15},(_,i)=>invoke(request(undefined,{'cf-connecting-ip':'192.0.2.'+(i+10)}),s.env)));assert.equal(s.calls.length,2);assert.equal(s.db.rows.get(key),ceiling);}});
test('D1 outage prevents AI and stores no raw personal input',async()=>{const s=setup();await invoke(request(),s.env);assert.ok(!JSON.stringify(s.db.bindings).includes('192.0.2.4'));assert.ok(!JSON.stringify(s.db.bindings).includes('架空デモ'));assert.ok(!JSON.stringify(s.db.bindings).includes('接客'));s.env.QUOTA={prepare(){throw Error('offline');}};assert.equal((await invoke(request(),s.env)).body.mode,'fallback');assert.equal(s.calls.length,1);});
test('AI failures and unsafe output preserve feedback',async()=>{for(const output of ['', 'https://bad.example', '5つ星です','a'.repeat(801),null]){const s=setup();s.env.AI.run=async()=>({response:output});assert.deepEqual((await invoke(request({text:'不満です',storeName:'s'}),s.env)).body,{draft:'不満です',mode:'fallback'});}const s=setup();s.env.AI.run=async()=>{throw Error('model offline');};assert.equal((await invoke(request(),s.env)).body.mode,'fallback');});
test('AI timeout returns original at 10 seconds (mock clock)',async()=>{const s=setup();s.env.AI.run=()=>new Promise(()=>{});const old=globalThis.setTimeout;let timeout;globalThis.setTimeout=(fn,ms)=>{if(ms!==10000)return old(fn,ms);timeout=ms;queueMicrotask(fn);return 0;};try{assert.equal((await invoke(request(),s.env)).body.mode,'fallback');assert.equal(timeout,10000);}finally{globalThis.setTimeout=old;}});
test('API never sends a browser fetch or Google POST',async()=>{const old=globalThis.fetch;globalThis.fetch=()=>{throw Error('Unexpected network');};try{const s=setup();assert.equal((await invoke(request(),s.env)).body.mode,'ai');assert.equal(s.calls.length,1);}finally{globalThis.fetch=old;}});
test('static response has restrictive security policy',async()=>{const r=await worker.fetch(new Request(origin),{ASSETS:{fetch:async()=>new Response('<h1>demo</h1>')}},{});assert.match(r.headers.get('content-security-policy'),/connect-src 'self'/);assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.equal(r.headers.get('referrer-policy'),'no-referrer');});
test('meaning reversal and invented recommendation must fall back',async()=>{for(const output of ['最高でした。また来たい','不満です。また来ます','満足です']){const s=setup();s.env.AI.run=async()=>({response:output});assert.deepEqual((await invoke(request({text:'不満です',storeName:'s'}),s.env)).body,{draft:'不満です',mode:'fallback'});}});
test('punctuation and whitespace only remain eligible',async()=>{const s=setup();s.env.AI.run=async()=>({response:'「不満です。改善してほしい。」'});assert.deepEqual((await invoke(request({text:'不満です 改善してほしい',storeName:'s'}),s.env)).body,{draft:'「不満です。改善してほしい。」',mode:'ai'});});
test('unterminated body is bounded by a read deadline',async()=>{const old=globalThis.setTimeout;let timeout,cancelled=false;globalThis.setTimeout=(fn,ms)=>{timeout=ms;queueMicrotask(fn);return 0;};try{const body=new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('{'));},cancel(){cancelled=true;}});await assert.rejects(boundedJSON(new Request(origin,{method:'POST',body,duplex:'half'})));assert.equal(timeout,3000);assert.equal(cancelled,true);}finally{globalThis.setTimeout=old;}});

test("expiry stops AI even with all bindings available",async()=>{Date.now=()=>Date.parse("2026-10-09T00:00:00Z");const s=setup();assert.equal((await invoke(request(),s.env)).body.mode,"fallback");assert.equal(s.calls.length,0);});

test('refused reservation releases rows already held: total and ip do not drain when day is exhausted',async()=>{const s=staleRead(setup({['day:'+day]:100,total:500}));await Promise.all(Array.from({length:20},(_,i)=>invoke(request(undefined,{'cf-connecting-ip':'192.0.2.'+(i+50)}),s.env)));assert.equal(s.calls.length,0);assert.equal(s.db.rows.get('total'),500);assert.equal(s.db.rows.get('day:'+day),100);for(const [key,count] of s.db.rows)if(key.startsWith('ip:'))assert.equal(count,0,key);});
test('refused total releases the ip row so the user keeps their attempts',async()=>{const s=staleRead(setup({total:1000}));assert.equal((await invoke(request(),s.env)).body.mode,'fallback');assert.equal(s.calls.length,0);for(const [key,count] of s.db.rows)if(key.startsWith('ip:'))assert.equal(count,0,key);assert.equal(s.db.rows.get('total'),1000);});
test('rejected model output keeps quota consumed (no refund after the model ran)',async()=>{const s=setup();s.env.AI.run=async()=>({response:'https://bad.example'});assert.equal((await invoke(request(),s.env)).body.mode,'fallback');assert.equal(s.db.rows.get('total'),1);assert.equal(s.db.rows.get('day:'+day),1);});
test('reserve, release and cleanup SQL behave on real SQLite',async(t)=>{const q=await sqliteQuota();if(!q)return t.skip('node:sqlite unavailable');const s=setup();s.env.QUOTA=q;q.db.exec("INSERT INTO quota VALUES ('day:"+day+"',100),('day:2026-09-20',7),('ip:2026-09-20:old',3),('total',40)");
  assert.equal((await invoke(request(),s.env)).body.mode,'fallback');assert.equal(s.calls.length,0);let rows=q.rows();assert.equal(rows.total,40,'total released after day refused');assert.equal(Object.entries(rows).filter(([k,v])=>k.startsWith('ip:'+day)&&v!==0).length,0,'ip row released');
  q.db.exec("UPDATE quota SET count=0 WHERE key='day:"+day+"'");assert.equal((await invoke(request(),s.env)).body.mode,'ai');rows=q.rows();assert.equal(rows.total,41);assert.equal(rows['day:'+day],1);assert.equal(rows['day:2026-09-20'],undefined,'stale day row purged');assert.equal(rows['ip:2026-09-20:old'],undefined,'stale ip row purged');assert.equal(Object.keys(rows).filter(k=>k.startsWith('ip:'+day)).length,1,'today ip row kept');});
test('ALLOWED_ORIGINS list replaces the same-origin default',async()=>{const s=setup();s.env.ALLOWED_ORIGINS='https://kuchikomi.example, https://hitokoto.example';assert.equal((await invoke(request(undefined,{origin:'https://kuchikomi.example'}),s.env)).status,200);assert.equal((await invoke(request(),s.env)).status,200);assert.equal((await invoke(request(undefined,{origin:'https://evil.example'}),s.env)).status,403);const req=request();req.headers.delete('origin');assert.equal((await invoke(req,s.env)).status,403);s.env.ALLOWED_ORIGINS='https://other.example';assert.equal((await invoke(request(),s.env)).status,403,'url.origin is not implied once the list is set');s.env.ALLOWED_ORIGINS='';assert.equal((await invoke(request(),s.env)).status,200,'empty list falls back to url.origin');});
test('markup is refused before AI; prose punctuation is returned verbatim under the plain-text contract',async()=>{for(const text of ['<b>最高</b>','a<script>x</script>','x > y','<'])assert.equal((await invoke(request({text,storeName:'s'}),setup().env)).status,400,text);let s=setup();assert.equal((await invoke(request({text:'ok',storeName:'<s>'}),s.env)).status,400);assert.equal(s.calls.length,0);s=setup();delete s.env.AI;const text=`A&W "最高" 'good' &amp;`;assert.deepEqual((await invoke(request({text,storeName:'s'}),s.env)).body,{draft:text,mode:'fallback'});const app=readFileSync(new URL('../public/app.js',import.meta.url),'utf8');assert.ok(app.includes("$('draft-text').value=draft"),'client renders draft through textarea.value');assert.ok(!/innerHTML\s*=[^;]*draft/.test(app),'client never assigns draft to innerHTML');});
test('bidi, zero-width, separators, C1, DEL, BOM and lone surrogates are refused; emoji sequences and newlines pass',()=>{for(const bad of ['\u{202e}','\u{200b}','\u{200c}','\u{200e}','\u{202a}','\u{2060}','\u{2064}','\u{2028}','\u{2029}','\u{7f}','\u{85}','\u{9f}','\u{feff}','\ud800','\udfff'])assert.ok(!validInput({text:'最高でした'+bad+'worst',storeName:'s'}),JSON.stringify(bad));assert.ok(!validInput({text:'ok',storeName:'x\u{202e}y'}));for(const good of ['😀','👨\u{200d}👩\u{200d}👧','❤\u{fe0f}','\t','\n','\r\n','＜＞＆','A&W','"x" \'y\''])assert.ok(validInput({text:'最高'+good+'でした',storeName:'s'}),JSON.stringify(good));});
test('failures are logged with reason codes only, never body or IP',async()=>{const s=setup();s.env.QUOTA={prepare(){throw Error('D1_ERROR: offline 192.0.2.4');}};await invoke(request({text:'秘密の本文',storeName:'架空デモ'}),s.env);const err=logs.filter(l=>l[0]==='error');assert.equal(err.length,1);assert.equal(err[0][1],'draft_fallback');assert.equal(err[0][2],'error');assert.equal(err[0][3],'Error');assert.ok(!JSON.stringify(logs).includes('192.0.2.4')&&!JSON.stringify(logs).includes('D1_ERROR'),'message must not be logged');const t=setup();t.env.AI.run=async()=>{throw Error('model offline');};await invoke(request(),t.env);assert.equal(logs.filter(l=>l[0]==='error').length,2);const u=setup();u.env.AI.run=async()=>({response:'5つ星です'});await invoke(request({text:'不満です',storeName:'s'}),u.env);assert.deepEqual(logs.at(-1),['warn','draft_fallback','ai_rejected_number','']);const v=setup({total:1000});await invoke(request(),v.env);assert.deepEqual(logs.at(-1),['warn','draft_fallback','ceiling','']);const v2=staleRead(setup({total:1000}));await invoke(request(),v2.env);assert.deepEqual(logs.at(-1),['warn','draft_fallback','quota_total','']);const w=setup();delete w.env.AI;await invoke(request(),w.env);assert.deepEqual(logs.at(-1),['warn','draft_fallback','bindings','']);const flat=JSON.stringify(logs.filter(l=>l[2]!=='error'));for(const secret of ['秘密の本文','架空デモ','接客','192.0.2.4'])assert.ok(!flat.includes(secret),secret);logs.length=0;const x=setup();await invoke(request(),x.env);assert.equal(logs.length,0,'success path logs nothing');});

